//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyEights.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrazyEights.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazy Eights.
        /// </summary>
        internal static string Caption_CrazyEights {
            get {
                return ResourceManager.GetString("Caption_CrazyEights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game In Progress.
        /// </summary>
        internal static string Caption_GameInProgress {
            get {
                return ResourceManager.GetString("Caption_GameInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard Suit: {0}.
        /// </summary>
        internal static string Caption_OverrideSuit {
            get {
                return ResourceManager.GetString("Caption_OverrideSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Caption_Score {
            get {
                return ResourceManager.GetString("Caption_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s your turn..
        /// </summary>
        internal static string Caption_YourTurn {
            get {
                return ResourceManager.GetString("Caption_YourTurn", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cars_small {
            get {
                object obj = ResourceManager.GetObject("cars_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fish_small {
            get {
                object obj = ResourceManager.GetObject("fish_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frog_small {
            get {
                object obj = ResourceManager.GetObject("frog_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap island_small {
            get {
                object obj = ResourceManager.GetObject("island_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lines_small {
            get {
                object obj = ResourceManager.GetObject("lines_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap magenta_small {
            get {
                object obj = ResourceManager.GetObject("magenta_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mineral_small {
            get {
                object obj = ResourceManager.GetObject("mineral_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_ClubsSuit {
            get {
                object obj = ResourceManager.GetObject("PNG_ClubsSuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_CrazyEights {
            get {
                object obj = ResourceManager.GetObject("PNG_CrazyEights", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_DiamondsSuit {
            get {
                object obj = ResourceManager.GetObject("PNG_DiamondsSuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_Forward {
            get {
                object obj = ResourceManager.GetObject("PNG_Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_HeartsSuit {
            get {
                object obj = ResourceManager.GetObject("PNG_HeartsSuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_Reverse {
            get {
                object obj = ResourceManager.GetObject("PNG_Reverse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_SpadesSuit {
            get {
                object obj = ResourceManager.GetObject("PNG_SpadesSuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_TableTile2 {
            get {
                object obj = ResourceManager.GetObject("PNG_TableTile2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to abandon your game in progress?.
        /// </summary>
        internal static string Prompt_AbandonGame {
            get {
                return ResourceManager.GetString("Prompt_AbandonGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        internal static string Prompt_EndGame {
            get {
                return ResourceManager.GetString("Prompt_EndGame", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rose_small {
            get {
                object obj = ResourceManager.GetObject("rose_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sanddunes_small {
            get {
                object obj = ResourceManager.GetObject("sanddunes_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sky_small {
            get {
                object obj = ResourceManager.GetObject("sky_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap space_small {
            get {
                object obj = ResourceManager.GetObject("space_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap squares_small {
            get {
                object obj = ResourceManager.GetObject("squares_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card..
        /// </summary>
        internal static string Text_InvalidCard {
            get {
                return ResourceManager.GetString("Text_InvalidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s {0}&apos;s turn..
        /// </summary>
        internal static string Text_OpponentTurn {
            get {
                return ResourceManager.GetString("Text_OpponentTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has won the game..
        /// </summary>
        internal static string Text_OpponentWonGame {
            get {
                return ResourceManager.GetString("Text_OpponentWonGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has won this hand..
        /// </summary>
        internal static string Text_OpponentWonHand {
            get {
                return ResourceManager.GetString("Text_OpponentWonHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} pts.
        /// </summary>
        internal static string Text_ScoreDisplay {
            get {
                return ResourceManager.GetString("Text_ScoreDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have won the game..
        /// </summary>
        internal static string Text_YouWonGame {
            get {
                return ResourceManager.GetString("Text_YouWonGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have won this hand..
        /// </summary>
        internal static string Text_YouWonHand {
            get {
                return ResourceManager.GetString("Text_YouWonHand", resourceCulture);
            }
        }
    }
}
